name: SimpleLifesteal
version: '1.0-SNAPSHOT'
main: com.jellypudding.simpleLifesteal.SimpleLifesteal
api-version: '1.21'
description: "Simple Lifesteal plugin"
author: AlphaAlex115
commands:
  hearts:
    description: Shows your current heart count.
    usage: /hearts
    permission: simplelifesteal.command.hearts
    permission-message: You do not have permission to use this command.
permissions:
  simplelifesteal.command.hearts:
    description: Allows using the /hearts command.
    default: true